### ISSUE TITLE
Datatable failing to load in certain circumstances

### ISSUE THREAD

**Issue by mrglassdanny** [mrglassdanny/vscode-moca-client#1]
Example column value is:
`java -cp $HELLO_WORLD blah.blah.blah.blah.blah -v FOO -W BAR -a http://localhost:1000/service -j $MYDIR/dir/file.xml -p 1000 -P 1001`

**Comment by lukerhoffman** [comment]
Issue with trunc(date, 'IW')  and to_char function w/i Oracle db. table does not load.

**Comment by ghost** [comment]
@lukerhoffman  -- issue here is with how mocaResults.ts is dealing with dates. I did some tests and this processing is unnecessary and actually hurting things. Removing this processing will fix your/all other date issues. I plan on doing so for the next release.

That being said, I am also looking into potential data grid alternatives.

**Comment by ghost** [comment]
Found the issue -- it is due to '$' in the code.

Since I am wrapping all cells in ``, $ is causing problems

**Comment by ghost** [comment]
This is fixed in v1.6.26!
